# Theme settings
doks:
    baseurl:
    color_theme:
    header:
        logo:
            # text: ResourceDAO
            image: true
        nav:
            - item_name: Join discord channel
              item_url: 'https://discord.gg/2PGtMw45y8'
            - item_name: Twitter
              item_url: 'https://twitter.com/resourcedao'
            - item_name: Github
              item_url: '#'
    footer:
        content:
            logo:
                text: ResourceDAO
                # image: true
            copyright: Copyright &copy; 2022. - ResourceDAO 
        social_list:
            - network_name: discord
              profile_url: 'https://discord.gg/2PGtMw45y8'
            - network_name: github
              profile_url: 'https://github.com/resourcedao/'
            - network_name: twitter
              profile_url: 'https://twitter.com/resourcedao'
            # - network_name: instagram
            #   profile_url: '#'
            # - network_name: youtube
            #   profile_url: '#'
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./resourcedao-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./resourcedao-theme/_layouts
includes_dir: ./resourcedao-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
